export const LIVE_DATA_REALITY = [
  {
    key: "profiles",
    label: "Profiles",
    table: "profiles",
    hasData: true,
    notes: "Profiles contain real seeded and demo users.",
  },
  {
    key: "objects",
    label: "Objects",
    table: "items",
    hasData: true,
    notes: "Objects/items contain real records and images. Matching now reserves items during active swaps and marks completed items as exchanged.",
  },
  {
    key: "matches",
    label: "Matching",
    table: "matches",
    hasData: true,
    notes: "Matching is persisted from Express Interest, duplicate-safe, and convertible to swaps.",
  },
  {
    key: "conversations",
    label: "Conversations",
    table: "conversations",
    hasData: true,
    notes: "Conversations are created from converted matches and can be opened through /chat?conversation=<id>.",
  },
  {
    key: "messages",
    label: "Messages",
    table: "messages",
    hasData: true,
    notes: "Messages persist to the database, support realtime subscription, and emit notifications.",
  },
  {
    key: "swaps",
    label: "Exchange",
    table: "swaps",
    hasData: true,
    notes: "Swaps contain exchange records and now support guarded status transitions: accepted, rejected, cancelled, completed.",
  },
  {
    key: "properties",
    label: "Properties",
    table: "properties",
    hasData: true,
    notes: "Property domain exists with live data.",
  },
  {
    key: "services",
    label: "Services",
    table: "services_listings",
    hasData: true,
    notes: "Services domain exists with live data.",
  },
  {
    key: "events",
    label: "Events",
    table: "events_listings",
    hasData: true,
    notes: "Events domain exists with live data.",
  },
] as const;
