export const LIVE_DATA_REALITY = [
  {
    key: "profiles",
    label: "Profiles",
    table: "profiles",
    hasData: true,
    notes: "Profiles contain real seeded and demo users.",
  },
  {
    key: "objects",
    label: "Objects",
    table: "items",
    hasData: true,
    notes: "Objects/items contain real records and images.",
  },
  {
    key: "matches",
    label: "Matching",
    table: "matches",
    hasData: false,
    notes: "Matching table exists but currently has no live rows.",
  },
  {
    key: "conversations",
    label: "Conversations",
    table: "conversations",
    hasData: false,
    notes: "Conversation structure exists but currently has no rows.",
  },
  {
    key: "messages",
    label: "Messages",
    table: "messages",
    hasData: false,
    notes: "Message persistence exists but currently has no live rows.",
  },
  {
    key: "swaps",
    label: "Exchange",
    table: "swaps",
    hasData: true,
    notes: "Swaps already contain exchange records.",
  },
  {
    key: "properties",
    label: "Properties",
    table: "properties",
    hasData: true,
    notes: "Property domain exists with live data.",
  },
  {
    key: "services",
    label: "Services",
    table: "services_listings",
    hasData: true,
    notes: "Services domain exists with live data.",
  },
  {
    key: "events",
    label: "Events",
    table: "events_listings",
    hasData: true,
    notes: "Events domain exists with live data.",
  },
] as const;
