import { nanoid } from "nanoid";
import { Announcement, Conversation, InfoStats, Item, MatchCandidate, SwapIntent, UserProfile } from "./types";

export const mockUser: UserProfile = {
  id: "user-1",
  email: "ana.swaply@example.com",
  displayName: "Ana Popescu",
  firstName: "Ana",
  avatarUrl: "https://ui-avatars.com/api/?name=Ana+Popescu",
  bio: "Găsesc obiecte noi pentru proiecte DIY și donez ce nu mai folosesc.",
  languages: ["ro", "en"],
  badge: "premium",
  location: {
    country: "România",
    region: "Cluj",
    city: "Cluj-Napoca",
    postalCode: "400000",
    coordinates: { lat: 46.77, lng: 23.59 },
    travelRadiusKm: 50,
  },
  visibility: {
    publicProfile: true,
    itemsVisibility: "public",
    showExactLocation: false,
    showLastSeen: true,
  },
  notifications: {
    email: true,
    push: true,
    chat: true,
    matches: true,
    swapUpdates: true,
  },
  swapPreferences: {
    logistics: "flexible",
    notes: "Prefer întâlniri în zone publice. Curier doar pentru obiecte mici.",
  },
  security: {
    twoFactorEnabled: true,
    method: "totp",
    passkeysEnabled: true,
  },
  stats: {
    tokens: 240,
    reputation: "trusted",
    completedSwaps: 12,
    activeListings: 4,
  },
};

const nowIso = new Date().toISOString();

export const mockItems: Item[] = [
  {
    id: "item-1",
    ownerId: mockUser.id,
    title: "Bicicletă urbană hibrid",
    category: "Sport & Outdoor",
    condition: "good",
    description: "Cadru ușor, nevoie de reglaj frâne. Ideală pentru oraș.",
    wishlist: "Accesorii camping sau un monitor 24\u201D",
    status: "active",
    isActive: true,
    createdAt: nowIso,
    location: "Cluj-Napoca",
    aiSuggestedTags: ["bicicletă", "transport", "outdoor"],
    userFinalTags: ["bicicletă", "urban", "second-hand"],
    photos: ["https://images.unsplash.com/photo-1529429617124-aee4a233f16b?w=400"],
  },
  {
    id: "item-2",
    ownerId: mockUser.id,
    title: "Set Lego Technic incomplet",
    category: "Hobby & Jocuri",
    condition: "used",
    description: "Lipsesc câteva piese, potrivit pentru proiecte custom.",
    wishlist: "Jocuri de societate sau puzzle-uri mari",
    status: "reserved",
    isActive: true,
    createdAt: nowIso,
    location: "Cluj-Napoca",
    aiSuggestedTags: ["lego", "technic", "piese"],
    userFinalTags: ["lego", "technic"],
    photos: ["https://images.unsplash.com/photo-1582719478248-54e9f2a41349?w=400"],
  },
  {
    id: "item-3",
    ownerId: "user-2",
    title: "Monitor 24'' IPS",
    category: "Electronică",
    condition: "good",
    description: "Funcționează perfect, fără pixeli morți. Include cablu HDMI.",
    wishlist: "Bicicletă urbană sau aparat foto instant",
    status: "active",
    isActive: true,
    createdAt: nowIso,
    location: "Brașov",
    aiSuggestedTags: ["monitor", "office"],
    userFinalTags: ["monitor", "24-inch"],
    photos: ["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400"],
  },
  // ── Property listings ──
  {
    id: "item-prop-1",
    ownerId: "user-2",
    title: "Cabană la munte – Bran",
    category: "Cazare",
    condition: "good",
    description: "Cabană 3 camere cu vedere la Bucegi, grădină, parcare. Perfect pentru iarnă sau vară.",
    wishlist: "Apartament la mare (Constanța / Mamaia) sau servicii de fotografie",
    status: "active",
    isActive: true,
    createdAt: nowIso,
    location: "Bran, Brașov",
    listingType: "property",
    houseProfile: {
      propertyType: "cabin",
      bedrooms: 3,
      bathrooms: 2,
      maxGuests: 6,
      amenities: ["wifi", "parking", "heating", "kitchen", "garden", "pet_friendly"],
      rules: ["no_smoking", "no_parties", "quiet_hours"],
      description: "Cabană tradițională renovată, cu șemineu și terasă acoperită.",
      neighborhood: "La 5 min de Castelul Bran, aproape de pârtii.",
      nearbyAttractions: "Castelul Bran, Peștera Dâmbovicioara, pârtii Poiana Brașov",
      transport: "Drum asfaltat, parcare privată",
      photos: ["https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=400"],
      availableDates: [{ from: "2026-03-01", to: "2026-09-30" }],
      minStayDays: 3,
      maxStayDays: 30,
      swapMode: "simultaneous",
      verified: false,
      insuranceReminder: true,
    },
    aiSuggestedTags: ["cabană", "munte", "Bran"],
    userFinalTags: ["cabană", "munte", "vacanță"],
    photos: ["https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=400"],
  },
  {
    id: "item-prop-2",
    ownerId: mockUser.id,
    title: "Apartament 2 camere – Mamaia",
    category: "Cazare",
    condition: "good",
    description: "Apartament modern cu vedere la mare, 50m de plajă. AC, WiFi, parcare.",
    wishlist: "Cabană la munte sau casă în Toscana",
    status: "active",
    isActive: true,
    createdAt: nowIso,
    location: "Mamaia, Constanța",
    listingType: "property",
    houseProfile: {
      propertyType: "apartment",
      bedrooms: 2,
      bathrooms: 1,
      maxGuests: 4,
      amenities: ["wifi", "parking", "ac", "kitchen", "tv", "washer", "balcony"],
      rules: ["no_smoking", "no_pets"],
      description: "Apartament modern complet mobilat, la etajul 3 cu lift.",
      neighborhood: "50m de plajă, restaurante și cluburi pe bulevardul principal.",
      nearbyAttractions: "Plaja Mamaia, Aqua Magic, Cazino Constanța",
      transport: "Transport public, parcare privată",
      photos: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400"],
      availableDates: [{ from: "2026-06-01", to: "2026-08-31" }],
      minStayDays: 5,
      maxStayDays: 21,
      swapMode: "simultaneous",
      verified: false,
      insuranceReminder: true,
    },
    aiSuggestedTags: ["apartament", "mare", "Mamaia"],
    userFinalTags: ["mare", "vacanță", "plajă"],
    photos: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400"],
  },
  // ── Service listings ──
  {
    id: "item-svc-1",
    ownerId: "user-3",
    title: "Lecții de fotografie",
    category: "Educație",
    condition: "new",
    description: "Fotograf profesionist cu 8 ani experiență oferă lecții de fotografie (portret, peisaj, street).",
    wishlist: "Lecții de programare, design web sau reparații biciclete",
    status: "active",
    isActive: true,
    createdAt: nowIso,
    location: "București",
    listingType: "service",
    serviceProfile: {
      category: "creative",
      skillName: "Fotografie",
      skillLevel: "expert",
      description: "Lecții individuale sau în grup mic (max 3 pers). Acoper: compoziție, lumină, editare.",
      portfolio: ["https://example.com/photo-portfolio"],
      hoursPerWeek: 8,
      delivery: "hybrid",
      hourlyEquivalent: 0,
    },
    aiSuggestedTags: ["fotografie", "lecții", "creativ"],
    userFinalTags: ["fotografie", "educație", "creativ"],
    photos: ["https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=400"],
  },
  {
    id: "item-svc-2",
    ownerId: mockUser.id,
    title: "Dezvoltare web (React / Next.js)",
    category: "IT & Tech",
    condition: "new",
    description: "Dezvoltator full-stack cu 5 ani experiență. Creez landing pages, aplicații web, integrări API.",
    wishlist: "Lecții de muzică, design grafic sau accesorii camping",
    status: "active",
    isActive: true,
    createdAt: nowIso,
    location: "Cluj-Napoca",
    listingType: "service",
    serviceProfile: {
      category: "technical",
      skillName: "Dezvoltare web",
      skillLevel: "expert",
      description: "React, Next.js, TypeScript, Supabase. Pot construi de la zero sau optimiza.",
      portfolio: [],
      hoursPerWeek: 10,
      delivery: "remote",
      hourlyEquivalent: 0,
    },
    aiSuggestedTags: ["programare", "web", "React"],
    userFinalTags: ["dev", "web", "fullstack"],
    photos: ["https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=400"],
  },
  {
    id: "item-svc-3",
    ownerId: "user-2",
    title: "Analiză statistică & Data Science",
    category: "IT & Tech",
    condition: "new",
    description: "Analist de date cu experiență în Python, R, Excel avansat. Analize, rapoarte, vizualizări.",
    wishlist: "Desen/pictură, lecții de gătit, sau obiecte de birou ergonomice",
    status: "active",
    isActive: true,
    createdAt: nowIso,
    location: "Brașov",
    listingType: "service",
    serviceProfile: {
      category: "technical",
      skillName: "Analiză statistică",
      skillLevel: "expert",
      description: "Analize de date, rapoarte statistice, vizualizări. Python, R, Power BI.",
      portfolio: [],
      hoursPerWeek: 6,
      delivery: "remote",
      hourlyEquivalent: 0,
    },
    aiSuggestedTags: ["statistică", "data", "analiză"],
    userFinalTags: ["data-science", "analiză", "Python"],
    photos: ["https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400"],
  },
];

export const mockAnnouncements: Announcement[] = [
  {
    id: "ann-1",
    message: "Funcție nouă: badge-urile Premium apar pe hartă cu vizibilitate extinsă.",
    priority: "info",
  },
  {
    id: "ann-2",
    message: "Profil incomplet – adaugă locația pentru a vedea utilizatori apropiați.",
    priority: "warning",
  },
];

export const mockMatches: MatchCandidate[] = [
  {
    id: "match-1",
    itemOffered: mockItems[0],
    itemRequested: mockItems[2],
    compatibilityScore: 92,
    tier: "strong",
    reasons: ["Categorii reciproc compatibile", "Valoare perceputa apropiata", "Aceeasi locatie — logistica simpla"],
    reason: "Categorii reciproc compatibile. Valoare perceputa apropiata. Aceeasi locatie — logistica simpla.",
    aiTrace: "hf:swaply-matcher-v1",
  },
  {
    id: "match-2",
    itemOffered: mockItems[1],
    itemRequested: mockItems[0],
    compatibilityScore: 75,
    tier: "good",
    reasons: ["Partenerul cauta categorie compatibila", "Intentii de schimb compatibile"],
    reason: "Partenerul cauta categorie compatibila. Intentii de schimb compatibile.",
    manualFallbackReason: "Analiza calculata local (scor cumulativ).",
  },
];

export const mockConversations: Conversation[] = [
  {
    id: "conv-1",
    participantId: "user-2",
    participantName: "Mihai Georgescu",
    participantBadge: "free",
    lastMessage: "Ne vedem la mall vineri?",
    updatedAt: nowIso,
    translationEnabled: true,
    messages: [
      {
        id: nanoid(),
        conversationId: "conv-1",
        senderId: "user-2",
        content: "Salut! Interesat de bicicleta ta.",
        createdAt: nowIso,
        attachments: [],
      },
      {
        id: nanoid(),
        conversationId: "conv-1",
        senderId: mockUser.id,
        content: "Putem discuta la mall vineri seara?",
        createdAt: nowIso,
        translated: true,
        attachments: [
          { id: nanoid(), name: "traseu.pdf", safe: true },
        ],
      },
    ],
  },
  {
    id: "conv-2",
    participantId: "user-3",
    participantName: "Ioana M.",
    participantBadge: "platinum",
    lastMessage: "Atașament verificat, putem confirma swap-ul.",
    updatedAt: nowIso,
    translationEnabled: false,
    messages: [
      {
        id: nanoid(),
        conversationId: "conv-2",
        senderId: "user-3",
        content: "Atașez dovada de expediere (scanează automat).",
        createdAt: nowIso,
        attachments: [
          { id: nanoid(), name: "awb.png", safe: true },
        ],
        moderated: true,
      },
    ],
  },
];

export const mockSwaps: SwapIntent[] = [
  {
    id: "swap-1",
    requesterId: mockUser.id,
    responderId: "user-2",
    requesterItemId: mockItems[0].id,
    responderItemId: mockItems[2].id,
    status: "accepted",
    logistics: {
      locationType: "public_spot",
      meetupPoint: "Iulius Mall, intrarea principală",
    },
    notifications: [
      "Notificare chat trimisă",
      "Remind cu 24h înainte de întâlnire",
    ],
    feedback: undefined,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockInfoStats: InfoStats = {
  globalSwaps: 8421,
  activeUsers: 3560,
  premiumShare: 0.38,
  tokensIssued: 52300,
};

export const mockFeatureToggles = {
  aiEnabled: true,
  mapsEnabled: false,
  cloudinaryEnabled: false,
  supabaseConfigured: false,
};

export function createEmptyItem(ownerId: string): Item {
  return {
    id: nanoid(),
    ownerId,
    title: "",
    category: "",
    condition: "good",
    description: "",
    wishlist: "",
    status: "active",
    isActive: true,
    createdAt: new Date().toISOString(),
    location: "",
    photos: [],
  };
}
