import { nanoid } from "nanoid";
import { Announcement, Conversation, InfoStats, Item, MatchCandidate, SwapIntent, UserProfile } from "./types";

export const mockUser: UserProfile = {
  id: "user-1",
  email: "emma.swaply@example.com",
  displayName: "Emma Smith",
  firstName: "Emma",
  avatarUrl: "https://ui-avatars.com/api/?name=Emma+Smith",
  bio: "Finding new items for DIY projects and giving away what I no longer use.",
  languages: ["en"],
  badge: "premium",
  location: {
    country: "United Kingdom",
    region: "England",
    city: "London",
    postalCode: "SW1A 1AA",
    coordinates: { lat: 51.51, lng: -0.13 },
    travelRadiusKm: 50,
  },
  visibility: {
    publicProfile: true,
    itemsVisibility: "public",
    showExactLocation: false,
    showLastSeen: true,
  },
  notifications: {
    email: true,
    push: true,
    chat: true,
    matches: true,
    swapUpdates: true,
  },
  swapPreferences: {
    logistics: "flexible",
    notes: "Prefer meetups in public places. Courier only for small items.",
  },
  security: {
    twoFactorEnabled: true,
    method: "totp",
    passkeysEnabled: true,
  },
  stats: {
    tokens: 240,
    reputation: "trusted",
    completedSwaps: 12,
    activeListings: 4,
  },
};

const nowIso = new Date().toISOString();

export const mockItems: Item[] = [
  {
    id: "item-1",
    ownerId: mockUser.id,
    title: "Urban Hybrid Bicycle",
    category: "Sport & Outdoor",
    condition: "good",
    description: "Lightweight frame, needs brake adjustment. Ideal for city use.",
    wishlist: "Camping accessories or a 24\u201D monitor",
    status: "active",
    isActive: true,
    createdAt: nowIso,
    location: "London",
    aiSuggestedTags: ["bicycle", "transport", "outdoor"],
    userFinalTags: ["bicycle", "urban", "second-hand"],
    photos: ["https://images.unsplash.com/photo-1529429617124-aee4a233f16b?w=400"],
  },
  {
    id: "item-2",
    ownerId: mockUser.id,
    title: "Incomplete Lego Technic Set",
    category: "Hobby & Games",
    condition: "used",
    description: "A few pieces missing, suitable for custom projects.",
    wishlist: "Board games or large puzzles",
    status: "reserved",
    isActive: true,
    createdAt: nowIso,
    location: "London",
    aiSuggestedTags: ["lego", "technic", "pieces"],
    userFinalTags: ["lego", "technic"],
    photos: ["https://images.unsplash.com/photo-1582719478248-54e9f2a41349?w=400"],
  },
  {
    id: "item-3",
    ownerId: "user-2",
    title: "Monitor 24'' IPS",
    category: "Electronics",
    condition: "good",
    description: "Works perfectly, no dead pixels. HDMI cable included.",
    wishlist: "Urban bicycle or instant camera",
    status: "active",
    isActive: true,
    createdAt: nowIso,
    location: "Manchester",
    aiSuggestedTags: ["monitor", "office"],
    userFinalTags: ["monitor", "24-inch"],
    photos: ["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400"],
  },
  // ── Property listings ──
  {
    id: "item-prop-1",
    ownerId: "user-2",
    title: "Mountain Cabin – Alps",
    category: "Accommodation",
    condition: "good",
    description: "3-bedroom cabin with mountain views, garden, parking. Perfect for winter or summer.",
    wishlist: "Beachfront apartment or photography services",
    status: "active",
    isActive: true,
    createdAt: nowIso,
    location: "Chamonix, France",
    listingType: "property",
    houseProfile: {
      propertyType: "cabin",
      bedrooms: 3,
      bathrooms: 2,
      maxGuests: 6,
      amenities: ["wifi", "parking", "heating", "kitchen", "garden", "pet_friendly"],
      rules: ["no_smoking", "no_parties", "quiet_hours"],
      description: "Renovated traditional cabin with fireplace and covered terrace.",
      neighborhood: "5 min from ski slopes, close to hiking trails.",
      nearbyAttractions: "Mont Blanc, Aiguille du Midi, ski resorts",
      transport: "Paved road, private parking",
      photos: ["https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=400"],
      availableDates: [{ from: "2026-03-01", to: "2026-09-30" }],
      minStayDays: 3,
      maxStayDays: 30,
      swapMode: "simultaneous",
      verified: false,
      insuranceReminder: true,
    },
    aiSuggestedTags: ["cabin", "mountain", "Alps"],
    userFinalTags: ["cabin", "mountain", "vacation"],
    photos: ["https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=400"],
  },
  {
    id: "item-prop-2",
    ownerId: mockUser.id,
    title: "2-Bedroom Apartment – Barcelona Beach",
    category: "Accommodation",
    condition: "good",
    description: "Modern apartment with sea view, 50m from the beach. AC, WiFi, parking.",
    wishlist: "Mountain cabin or house in Tuscany",
    status: "active",
    isActive: true,
    createdAt: nowIso,
    location: "Barcelona, Spain",
    listingType: "property",
    houseProfile: {
      propertyType: "apartment",
      bedrooms: 2,
      bathrooms: 1,
      maxGuests: 4,
      amenities: ["wifi", "parking", "ac", "kitchen", "tv", "washer", "balcony"],
      rules: ["no_smoking", "no_pets"],
      description: "Fully furnished modern apartment on the 3rd floor with elevator.",
      neighborhood: "50m from the beach, restaurants and clubs on the main boulevard.",
      nearbyAttractions: "Barceloneta Beach, La Sagrada Familia, Park Guell",
      transport: "Public transport, private parking",
      photos: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400"],
      availableDates: [{ from: "2026-06-01", to: "2026-08-31" }],
      minStayDays: 5,
      maxStayDays: 21,
      swapMode: "simultaneous",
      verified: false,
      insuranceReminder: true,
    },
    aiSuggestedTags: ["apartment", "beach", "Barcelona"],
    userFinalTags: ["beach", "vacation", "seaside"],
    photos: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400"],
  },
  // ── Service listings ──
  {
    id: "item-svc-1",
    ownerId: "user-3",
    title: "Photography Lessons",
    category: "Education",
    condition: "new",
    description: "Professional photographer with 8 years of experience offering photography lessons (portrait, landscape, street).",
    wishlist: "Programming lessons, web design, or bicycle repairs",
    status: "active",
    isActive: true,
    createdAt: nowIso,
    location: "London",
    listingType: "service",
    serviceProfile: {
      category: "creative",
      skillName: "Photography",
      skillLevel: "expert",
      description: "Individual or small group lessons (max 3 people). Covers: composition, lighting, editing.",
      portfolio: ["https://example.com/photo-portfolio"],
      hoursPerWeek: 8,
      delivery: "hybrid",
      hourlyEquivalent: 0,
    },
    aiSuggestedTags: ["photography", "lessons", "creative"],
    userFinalTags: ["photography", "education", "creative"],
    photos: ["https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=400"],
  },
  {
    id: "item-svc-2",
    ownerId: mockUser.id,
    title: "Web Development (React / Next.js)",
    category: "IT & Tech",
    condition: "new",
    description: "Full-stack developer with 5 years of experience. I build landing pages, web apps, and API integrations.",
    wishlist: "Music lessons, graphic design, or camping accessories",
    status: "active",
    isActive: true,
    createdAt: nowIso,
    location: "Berlin",
    listingType: "service",
    serviceProfile: {
      category: "technical",
      skillName: "Web Development",
      skillLevel: "expert",
      description: "React, Next.js, TypeScript, Supabase. Can build from scratch or optimize.",
      portfolio: [],
      hoursPerWeek: 10,
      delivery: "remote",
      hourlyEquivalent: 0,
    },
    aiSuggestedTags: ["programming", "web", "React"],
    userFinalTags: ["dev", "web", "fullstack"],
    photos: ["https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=400"],
  },
  {
    id: "item-svc-3",
    ownerId: "user-2",
    title: "Statistical Analysis & Data Science",
    category: "IT & Tech",
    condition: "new",
    description: "Data analyst experienced in Python, R, and advanced Excel. Analyses, reports, visualizations.",
    wishlist: "Drawing/painting, cooking lessons, or ergonomic office items",
    status: "active",
    isActive: true,
    createdAt: nowIso,
    location: "Amsterdam",
    listingType: "service",
    serviceProfile: {
      category: "technical",
      skillName: "Statistical Analysis",
      skillLevel: "expert",
      description: "Data analyses, statistical reports, visualizations. Python, R, Power BI.",
      portfolio: [],
      hoursPerWeek: 6,
      delivery: "remote",
      hourlyEquivalent: 0,
    },
    aiSuggestedTags: ["statistics", "data", "analysis"],
    userFinalTags: ["data-science", "analysis", "Python"],
    photos: ["https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400"],
  },
];

export const mockAnnouncements: Announcement[] = [
  {
    id: "ann-1",
    message: "New feature: Premium badges now appear on the map with extended visibility.",
    priority: "info",
  },
  {
    id: "ann-2",
    message: "Incomplete profile — add your location to see nearby users.",
    priority: "warning",
  },
];

export const mockMatches: MatchCandidate[] = [
  {
    id: "match-1",
    itemOffered: mockItems[0],
    itemRequested: mockItems[2],
    compatibilityScore: 92,
    tier: "strong",
    reasons: ["Mutually compatible categories", "Similar perceived value", "Same location — simple logistics"],
    reason: "Mutually compatible categories. Similar perceived value. Same location — simple logistics.",
    aiTrace: "hf:swaply-matcher-v1",
  },
  {
    id: "match-2",
    itemOffered: mockItems[1],
    itemRequested: mockItems[0],
    compatibilityScore: 75,
    tier: "good",
    reasons: ["Partner is looking for a compatible category", "Compatible swap intentions"],
    reason: "Partner is looking for a compatible category. Compatible swap intentions.",
    manualFallbackReason: "Analysis calculated locally (cumulative score).",
  },
];

export const mockConversations: Conversation[] = [
  {
    id: "conv-1",
    participantId: "user-2",
    participantName: "James Garcia",
    participantBadge: "free",
    lastMessage: "See you at the mall on Friday?",
    updatedAt: nowIso,
    translationEnabled: true,
    messages: [
      {
        id: nanoid(),
        conversationId: "conv-1",
        senderId: "user-2",
        content: "Hi! Interested in your bicycle.",
        createdAt: nowIso,
        attachments: [],
      },
      {
        id: nanoid(),
        conversationId: "conv-1",
        senderId: mockUser.id,
        content: "Can we meet at the mall on Friday evening?",
        createdAt: nowIso,
        translated: true,
        attachments: [
          { id: nanoid(), name: "route.pdf", safe: true },
        ],
      },
    ],
  },
  {
    id: "conv-2",
    participantId: "user-3",
    participantName: "Sofia K.",
    participantBadge: "platinum",
    lastMessage: "Attachment verified, we can confirm the swap.",
    updatedAt: nowIso,
    translationEnabled: false,
    messages: [
      {
        id: nanoid(),
        conversationId: "conv-2",
        senderId: "user-3",
        content: "Attaching proof of shipment (auto-scanned).",
        createdAt: nowIso,
        attachments: [
          { id: nanoid(), name: "awb.png", safe: true },
        ],
        moderated: true,
      },
    ],
  },
];

export const mockSwaps: SwapIntent[] = [
  {
    id: "swap-1",
    requesterId: mockUser.id,
    responderId: "user-2",
    requesterItemId: mockItems[0].id,
    responderItemId: mockItems[2].id,
    status: "accepted",
    logistics: {
      locationType: "public_spot",
      meetupPoint: "Central Mall, main entrance",
    },
    notifications: [
      "Chat notification sent",
      "Reminder 24h before meetup",
    ],
    feedback: undefined,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockInfoStats: InfoStats = {
  globalSwaps: 8421,
  activeUsers: 3560,
  premiumShare: 0.38,
  tokensIssued: 52300,
};

export const mockFeatureToggles = {
  aiEnabled: true,
  mapsEnabled: false,
  cloudinaryEnabled: false,
  supabaseConfigured: false,
};

export function createEmptyItem(ownerId: string): Item {
  return {
    id: nanoid(),
    ownerId,
    title: "",
    category: "",
    condition: "good",
    description: "",
    wishlist: "",
    status: "active",
    isActive: true,
    createdAt: new Date().toISOString(),
    location: "",
    photos: [],
  };
}
