import { locales, type Locale } from "./config";

type PublicCoreUi = {
  preview: string;
  login: string;
  matchingTitle: string;
  messagesTitle: string;
  exchangeTitle: string;
  explore: string;
  browseAll: string;
  filters: string;
  addObject: string;
  conversations: string;
  secureChat: string;
  matchingDescription: string;
  messagesDescription: string;
  exchangeDescription: string;
};

export const publicCoreUi = {
  en: { preview:"Preview", login:"Sign in", matchingTitle:"Matching", messagesTitle:"Messages", exchangeTitle:"Exchange", explore:"Explore", browseAll:"Browse all", filters:"Filters", addObject:"Add object", conversations:"Conversations", secureChat:"Secure chat", matchingDescription:"Compare what you offer with what others want and discover compatible swaps.", messagesDescription:"Keep each swap conversation, shared decisions and next steps in one place.", exchangeDescription:"Turn an agreed match into a clear handover with logistics, confirmation and feedback." },
  ro: { preview:"Previzualizare", login:"Autentificare", matchingTitle:"Potriviri", messagesTitle:"Mesaje", exchangeTitle:"Schimb", explore:"Explorează", browseAll:"Vezi toate", filters:"Filtre", addObject:"Adaugă obiect", conversations:"Conversații", secureChat:"Chat securizat", matchingDescription:"Compară ceea ce oferi cu ceea ce caută ceilalți și descoperă schimburi compatibile.", messagesDescription:"Păstrează într-un singur loc fiecare conversație de schimb, deciziile comune și pașii următori.", exchangeDescription:"Transformă o potrivire acceptată într-o predare clară, cu logistică, confirmare și feedback." },
  fr: { preview:"Aperçu", login:"Se connecter", matchingTitle:"Correspondances", messagesTitle:"Messages", exchangeTitle:"Échange", explore:"Explorer", browseAll:"Tout parcourir", filters:"Filtres", addObject:"Ajouter un objet", conversations:"Conversations", secureChat:"Chat sécurisé", matchingDescription:"Comparez ce que vous proposez avec ce que recherchent les autres et découvrez des échanges compatibles.", messagesDescription:"Regroupez chaque conversation d’échange, les décisions partagées et les prochaines étapes au même endroit.", exchangeDescription:"Transformez une correspondance acceptée en remise claire avec logistique, confirmation et avis." },
  de: { preview:"Vorschau", login:"Anmelden", matchingTitle:"Passende Tausche", messagesTitle:"Nachrichten", exchangeTitle:"Tausch", explore:"Entdecken", browseAll:"Alle ansehen", filters:"Filter", addObject:"Objekt hinzufügen", conversations:"Unterhaltungen", secureChat:"Sicherer Chat", matchingDescription:"Vergleiche dein Angebot mit den Wünschen anderer und entdecke passende Tauschmöglichkeiten.", messagesDescription:"Behalte jede Tauschunterhaltung, gemeinsame Entscheidungen und nächste Schritte an einem Ort.", exchangeDescription:"Mache aus einem vereinbarten Match eine klare Übergabe mit Logistik, Bestätigung und Feedback." },
  es: { preview:"Vista previa", login:"Iniciar sesión", matchingTitle:"Coincidencias", messagesTitle:"Mensajes", exchangeTitle:"Intercambio", explore:"Explorar", browseAll:"Ver todo", filters:"Filtros", addObject:"Añadir objeto", conversations:"Conversaciones", secureChat:"Chat seguro", matchingDescription:"Compara lo que ofreces con lo que buscan los demás y descubre intercambios compatibles.", messagesDescription:"Mantén cada conversación de intercambio, las decisiones compartidas y los próximos pasos en un solo lugar.", exchangeDescription:"Convierte una coincidencia aceptada en una entrega clara con logística, confirmación y valoración." },
  it: { preview:"Anteprima", login:"Accedi", matchingTitle:"Abbinamenti", messagesTitle:"Messaggi", exchangeTitle:"Scambio", explore:"Esplora", browseAll:"Sfoglia tutto", filters:"Filtri", addObject:"Aggiungi oggetto", conversations:"Conversazioni", secureChat:"Chat sicura", matchingDescription:"Confronta ciò che offri con ciò che cercano gli altri e scopri scambi compatibili.", messagesDescription:"Tieni in un unico posto ogni conversazione di scambio, le decisioni condivise e i prossimi passi.", exchangeDescription:"Trasforma un abbinamento accettato in una consegna chiara con logistica, conferma e feedback." },
  pt: { preview:"Pré-visualização", login:"Entrar", matchingTitle:"Correspondências", messagesTitle:"Mensagens", exchangeTitle:"Troca", explore:"Explorar", browseAll:"Ver tudo", filters:"Filtros", addObject:"Adicionar objeto", conversations:"Conversas", secureChat:"Chat seguro", matchingDescription:"Compare o que oferece com o que outras pessoas procuram e descubra trocas compatíveis.", messagesDescription:"Mantenha cada conversa de troca, decisões partilhadas e próximos passos num só lugar.", exchangeDescription:"Transforme uma correspondência aceite numa entrega clara com logística, confirmação e avaliação." },
  nl: { preview:"Voorbeeld", login:"Inloggen", matchingTitle:"Matches", messagesTitle:"Berichten", exchangeTitle:"Ruil", explore:"Ontdekken", browseAll:"Alles bekijken", filters:"Filters", addObject:"Object toevoegen", conversations:"Gesprekken", secureChat:"Veilige chat", matchingDescription:"Vergelijk wat je aanbiedt met wat anderen zoeken en ontdek passende ruilmogelijkheden.", messagesDescription:"Houd elk ruilgesprek, gezamenlijke beslissingen en volgende stappen op één plek.", exchangeDescription:"Maak van een geaccepteerde match een duidelijke overdracht met logistiek, bevestiging en feedback." },
  pl: { preview:"Podgląd", login:"Zaloguj się", matchingTitle:"Dopasowania", messagesTitle:"Wiadomości", exchangeTitle:"Wymiana", explore:"Odkrywaj", browseAll:"Przeglądaj wszystko", filters:"Filtry", addObject:"Dodaj przedmiot", conversations:"Rozmowy", secureChat:"Bezpieczny czat", matchingDescription:"Porównaj to, co oferujesz, z tym, czego szukają inni, i odkryj zgodne wymiany.", messagesDescription:"Przechowuj każdą rozmowę o wymianie, wspólne ustalenia i kolejne kroki w jednym miejscu.", exchangeDescription:"Zamień zaakceptowane dopasowanie w jasne przekazanie z logistyką, potwierdzeniem i opinią." },
  el: { preview:"Προεπισκόπηση", login:"Σύνδεση", matchingTitle:"Αντιστοιχίσεις", messagesTitle:"Μηνύματα", exchangeTitle:"Ανταλλαγή", explore:"Εξερεύνηση", browseAll:"Προβολή όλων", filters:"Φίλτρα", addObject:"Προσθήκη αντικειμένου", conversations:"Συνομιλίες", secureChat:"Ασφαλής συνομιλία", matchingDescription:"Συγκρίνετε όσα προσφέρετε με όσα αναζητούν οι άλλοι και βρείτε συμβατές ανταλλαγές.", messagesDescription:"Κρατήστε κάθε συζήτηση ανταλλαγής, τις κοινές αποφάσεις και τα επόμενα βήματα σε ένα σημείο.", exchangeDescription:"Μετατρέψτε μια αποδεκτή αντιστοίχιση σε σαφή παράδοση με οργάνωση, επιβεβαίωση και αξιολόγηση." },
  hu: { preview:"Előnézet", login:"Bejelentkezés", matchingTitle:"Párosítások", messagesTitle:"Üzenetek", exchangeTitle:"Csere", explore:"Felfedezés", browseAll:"Összes megtekintése", filters:"Szűrők", addObject:"Tárgy hozzáadása", conversations:"Beszélgetések", secureChat:"Biztonságos chat", matchingDescription:"Hasonlítsd össze, amit kínálsz, azzal, amit mások keresnek, és találj összeillő cseréket.", messagesDescription:"Tarts minden cserebeszélgetést, közös döntést és következő lépést egy helyen.", exchangeDescription:"Az elfogadott párosításból legyen egyértelmű átadás logisztikával, megerősítéssel és visszajelzéssel." },
  bg: { preview:"Преглед", login:"Вход", matchingTitle:"Съвпадения", messagesTitle:"Съобщения", exchangeTitle:"Размяна", explore:"Разгледай", browseAll:"Виж всички", filters:"Филтри", addObject:"Добави обект", conversations:"Разговори", secureChat:"Защитен чат", matchingDescription:"Сравнете това, което предлагате, с това, което търсят другите, и открийте съвместими размени.", messagesDescription:"Съхранявайте всеки разговор за размяна, общите решения и следващите стъпки на едно място.", exchangeDescription:"Превърнете прието съвпадение в ясна размяна с логистика, потвърждение и обратна връзка." },
  cs: { preview:"Náhled", login:"Přihlásit se", matchingTitle:"Shody", messagesTitle:"Zprávy", exchangeTitle:"Výměna", explore:"Prozkoumat", browseAll:"Zobrazit vše", filters:"Filtry", addObject:"Přidat předmět", conversations:"Konverzace", secureChat:"Bezpečný chat", matchingDescription:"Porovnejte svou nabídku s tím, co hledají ostatní, a objevte kompatibilní výměny.", messagesDescription:"Mějte každou konverzaci o výměně, společná rozhodnutí a další kroky na jednom místě.", exchangeDescription:"Proměňte přijatou shodu v přehledné předání s logistikou, potvrzením a zpětnou vazbou." },
  sk: { preview:"Náhľad", login:"Prihlásiť sa", matchingTitle:"Zhody", messagesTitle:"Správy", exchangeTitle:"Výmena", explore:"Objavovať", browseAll:"Zobraziť všetko", filters:"Filtre", addObject:"Pridať predmet", conversations:"Konverzácie", secureChat:"Bezpečný chat", matchingDescription:"Porovnajte svoju ponuku s tým, čo hľadajú ostatní, a objavte kompatibilné výmeny.", messagesDescription:"Majte každú konverzáciu o výmene, spoločné rozhodnutia a ďalšie kroky na jednom mieste.", exchangeDescription:"Premeňte prijatú zhodu na jasné odovzdanie s logistikou, potvrdením a spätnou väzbou." },
  hr: { preview:"Pregled", login:"Prijava", matchingTitle:"Podudaranja", messagesTitle:"Poruke", exchangeTitle:"Zamjena", explore:"Istraži", browseAll:"Pregledaj sve", filters:"Filtri", addObject:"Dodaj predmet", conversations:"Razgovori", secureChat:"Siguran chat", matchingDescription:"Usporedite ono što nudite s onim što drugi traže i pronađite kompatibilne zamjene.", messagesDescription:"Držite svaki razgovor o zamjeni, zajedničke odluke i sljedeće korake na jednom mjestu.", exchangeDescription:"Pretvorite prihvaćeno podudaranje u jasnu primopredaju uz logistiku, potvrdu i povratne informacije." },
  sl: { preview:"Predogled", login:"Prijava", matchingTitle:"Ujemanja", messagesTitle:"Sporočila", exchangeTitle:"Menjava", explore:"Razišči", browseAll:"Poglej vse", filters:"Filtri", addObject:"Dodaj predmet", conversations:"Pogovori", secureChat:"Varen klepet", matchingDescription:"Primerjajte svojo ponudbo s tem, kar iščejo drugi, in odkrijte združljive menjave.", messagesDescription:"Naj bodo vsak pogovor o menjavi, skupne odločitve in naslednji koraki na enem mestu.", exchangeDescription:"Sprejeto ujemanje spremenite v jasno predajo z logistiko, potrditvijo in povratnimi informacijami." },
  sr: { preview:"Преглед", login:"Пријава", matchingTitle:"Подударања", messagesTitle:"Поруке", exchangeTitle:"Размена", explore:"Истражи", browseAll:"Прегледај све", filters:"Филтери", addObject:"Додај предмет", conversations:"Разговори", secureChat:"Безбедан чет", matchingDescription:"Упоредите оно што нудите са оним што други траже и пронађите компатибилне размене.", messagesDescription:"Држите сваки разговор о размени, заједничке одлуке и следеће кораке на једном месту.", exchangeDescription:"Претворите прихваћено подударање у јасну примопредају са логистиком, потврдом и повратним информацијама." },
  sv: { preview:"Förhandsvisning", login:"Logga in", matchingTitle:"Matchningar", messagesTitle:"Meddelanden", exchangeTitle:"Byte", explore:"Utforska", browseAll:"Visa alla", filters:"Filter", addObject:"Lägg till objekt", conversations:"Konversationer", secureChat:"Säker chatt", matchingDescription:"Jämför det du erbjuder med det andra söker och hitta kompatibla byten.", messagesDescription:"Samla varje byteskonversation, gemensamma beslut och nästa steg på ett ställe.", exchangeDescription:"Gör en accepterad matchning till en tydlig överlämning med logistik, bekräftelse och feedback." },
  da: { preview:"Forhåndsvisning", login:"Log ind", matchingTitle:"Match", messagesTitle:"Beskeder", exchangeTitle:"Bytte", explore:"Udforsk", browseAll:"Se alle", filters:"Filtre", addObject:"Tilføj objekt", conversations:"Samtaler", secureChat:"Sikker chat", matchingDescription:"Sammenlign det, du tilbyder, med det andre søger, og find kompatible bytter.", messagesDescription:"Saml hver byttesamtale, fælles beslutninger og næste skridt ét sted.", exchangeDescription:"Gør et accepteret match til en tydelig overdragelse med logistik, bekræftelse og feedback." },
  fi: { preview:"Esikatselu", login:"Kirjaudu", matchingTitle:"Osumat", messagesTitle:"Viestit", exchangeTitle:"Vaihto", explore:"Tutustu", browseAll:"Selaa kaikkia", filters:"Suodattimet", addObject:"Lisää kohde", conversations:"Keskustelut", secureChat:"Turvallinen chat", matchingDescription:"Vertaa tarjoamaasi siihen, mitä muut etsivät, ja löydä yhteensopivia vaihtoja.", messagesDescription:"Pidä kaikki vaihtokeskustelut, yhteiset päätökset ja seuraavat vaiheet yhdessä paikassa.", exchangeDescription:"Muuta hyväksytty osuma selkeäksi luovutukseksi logistiikan, vahvistuksen ja palautteen avulla." },
  no: { preview:"Forhåndsvisning", login:"Logg inn", matchingTitle:"Matcher", messagesTitle:"Meldinger", exchangeTitle:"Bytte", explore:"Utforsk", browseAll:"Se alle", filters:"Filtre", addObject:"Legg til objekt", conversations:"Samtaler", secureChat:"Sikker chat", matchingDescription:"Sammenlign det du tilbyr med det andre leter etter, og finn kompatible bytter.", messagesDescription:"Samle hver byttesamtale, felles beslutninger og neste steg på ett sted.", exchangeDescription:"Gjør en akseptert match til en tydelig overlevering med logistikk, bekreftelse og tilbakemelding." },
  lt: { preview:"Peržiūra", login:"Prisijungti", matchingTitle:"Atitikmenys", messagesTitle:"Žinutės", exchangeTitle:"Mainai", explore:"Naršyti", browseAll:"Peržiūrėti viską", filters:"Filtrai", addObject:"Pridėti objektą", conversations:"Pokalbiai", secureChat:"Saugus pokalbis", matchingDescription:"Palyginkite tai, ką siūlote, su tuo, ko ieško kiti, ir raskite suderinamus mainus.", messagesDescription:"Laikykite visus mainų pokalbius, bendrus sprendimus ir kitus žingsnius vienoje vietoje.", exchangeDescription:"Paverskite priimtą atitikmenį aiškiu perdavimu su logistika, patvirtinimu ir atsiliepimu." },
  lv: { preview:"Priekšskatījums", login:"Pierakstīties", matchingTitle:"Atbilstības", messagesTitle:"Ziņojumi", exchangeTitle:"Maiņa", explore:"Izpētīt", browseAll:"Skatīt visu", filters:"Filtri", addObject:"Pievienot objektu", conversations:"Sarunas", secureChat:"Droša tērzēšana", matchingDescription:"Salīdziniet savu piedāvājumu ar to, ko meklē citi, un atrodiet saderīgas maiņas.", messagesDescription:"Glabājiet visas maiņas sarunas, kopīgos lēmumus un nākamos soļus vienuviet.", exchangeDescription:"Pārvērtiet apstiprinātu atbilstību skaidrā nodošanā ar loģistiku, apstiprinājumu un atsauksmi." },
  et: { preview:"Eelvaade", login:"Logi sisse", matchingTitle:"Sobivused", messagesTitle:"Sõnumid", exchangeTitle:"Vahetus", explore:"Avasta", browseAll:"Vaata kõiki", filters:"Filtrid", addObject:"Lisa objekt", conversations:"Vestlused", secureChat:"Turvaline vestlus", matchingDescription:"Võrdle oma pakkumist sellega, mida teised otsivad, ja leia sobivad vahetused.", messagesDescription:"Hoia kõik vahetusvestlused, ühised otsused ja järgmised sammud ühes kohas.", exchangeDescription:"Muuda kinnitatud sobivus selgeks üleandmiseks koos logistika, kinnituse ja tagasisidega." },
  ga: { preview:"Réamhamharc", login:"Sínigh isteach", matchingTitle:"Meaitseálacha", messagesTitle:"Teachtaireachtaí", exchangeTitle:"Malartú", explore:"Fiosraigh", browseAll:"Brabhsáil uile", filters:"Scagairí", addObject:"Cuir rud leis", conversations:"Comhráite", secureChat:"Comhrá slán", matchingDescription:"Cuir an méid a thairgeann tú i gcomparáid leis an méid atá daoine eile ag lorg agus aimsigh malartuithe oiriúnacha.", messagesDescription:"Coinnigh gach comhrá malartaithe, cinneadh comhroinnte agus céim eile in aon áit amháin.", exchangeDescription:"Déan aistriú soiléir de mheaitseáil ghlactha le lóistíocht, deimhniú agus aiseolas." },
  mt: { preview:"Previżjoni", login:"Idħol", matchingTitle:"Tqabbil", messagesTitle:"Messaġġi", exchangeTitle:"Skambju", explore:"Esplora", browseAll:"Ara kollox", filters:"Filtri", addObject:"Żid oġġett", conversations:"Konverżazzjonijiet", secureChat:"Chat sigur", matchingDescription:"Qabbel dak li toffri ma’ dak li qed ifittxu oħrajn u sib skambji kompatibbli.", messagesDescription:"Żomm kull konverżazzjoni ta’ skambju, deċiżjoni maqsuma u pass li jmiss f’post wieħed.", exchangeDescription:"Ibdel tqabbil aċċettat fi trasferiment ċar b’loġistika, konferma u feedback." },
  ru: { preview:"Предпросмотр", login:"Войти", matchingTitle:"Совпадения", messagesTitle:"Сообщения", exchangeTitle:"Обмен", explore:"Обзор", browseAll:"Смотреть все", filters:"Фильтры", addObject:"Добавить объект", conversations:"Диалоги", secureChat:"Безопасный чат", matchingDescription:"Сравните то, что вы предлагаете, с тем, что ищут другие, и найдите подходящие обмены.", messagesDescription:"Храните все обсуждения обмена, совместные решения и следующие шаги в одном месте.", exchangeDescription:"Превратите согласованное совпадение в понятную передачу с логистикой, подтверждением и отзывом." },
  tr: { preview:"Önizleme", login:"Giriş yap", matchingTitle:"Eşleşmeler", messagesTitle:"Mesajlar", exchangeTitle:"Takas", explore:"Keşfet", browseAll:"Tümünü gör", filters:"Filtreler", addObject:"Nesne ekle", conversations:"Konuşmalar", secureChat:"Güvenli sohbet", matchingDescription:"Sunduğunuz şeyi başkalarının aradıklarıyla karşılaştırın ve uyumlu takasları keşfedin.", messagesDescription:"Her takas konuşmasını, ortak kararları ve sonraki adımları tek yerde tutun.", exchangeDescription:"Kabul edilen bir eşleşmeyi lojistik, onay ve geri bildirimle net bir teslim sürecine dönüştürün." },
  ar: { preview:"معاينة", login:"تسجيل الدخول", matchingTitle:"المطابقات", messagesTitle:"الرسائل", exchangeTitle:"التبادل", explore:"استكشاف", browseAll:"عرض الكل", filters:"عوامل التصفية", addObject:"إضافة غرض", conversations:"المحادثات", secureChat:"دردشة آمنة", matchingDescription:"قارن ما تعرضه بما يبحث عنه الآخرون واكتشف عمليات تبادل متوافقة.", messagesDescription:"احتفظ بكل محادثة تبادل والقرارات المشتركة والخطوات التالية في مكان واحد.", exchangeDescription:"حوّل التطابق المقبول إلى عملية تسليم واضحة تشمل الترتيبات والتأكيد والتقييم." },
  zh: { preview:"预览", login:"登录", matchingTitle:"匹配", messagesTitle:"消息", exchangeTitle:"交换", explore:"探索", browseAll:"浏览全部", filters:"筛选", addObject:"添加物品", conversations:"对话", secureChat:"安全聊天", matchingDescription:"将你提供的内容与他人的需求进行比较，发现合适的交换机会。", messagesDescription:"将每次交换对话、共同决定和后续步骤集中在一个地方。", exchangeDescription:"把已达成的匹配变成清晰的交接流程，包括物流、确认和反馈。" },
  hi: { preview:"पूर्वावलोकन", login:"साइन इन", matchingTitle:"मिलान", messagesTitle:"संदेश", exchangeTitle:"अदला-बदली", explore:"खोजें", browseAll:"सभी देखें", filters:"फ़िल्टर", addObject:"वस्तु जोड़ें", conversations:"बातचीत", secureChat:"सुरक्षित चैट", matchingDescription:"आप जो पेश कर रहे हैं उसकी तुलना दूसरों की ज़रूरतों से करें और उपयुक्त अदला-बदली खोजें।", messagesDescription:"हर अदला-बदली की बातचीत, साझा निर्णय और अगले कदम एक ही जगह रखें।", exchangeDescription:"स्वीकृत मिलान को लॉजिस्टिक्स, पुष्टि और प्रतिक्रिया के साथ स्पष्ट हस्तांतरण में बदलें।" },
  bn: { preview:"পূর্বরূপ", login:"সাইন ইন", matchingTitle:"মিল", messagesTitle:"বার্তা", exchangeTitle:"বিনিময়", explore:"ঘুরে দেখুন", browseAll:"সব দেখুন", filters:"ফিল্টার", addObject:"বস্তু যোগ করুন", conversations:"কথোপকথন", secureChat:"নিরাপদ চ্যাট", matchingDescription:"আপনি যা দিচ্ছেন তা অন্যরা যা খুঁজছেন তার সঙ্গে তুলনা করুন এবং মানানসই বিনিময় খুঁজে নিন।", messagesDescription:"প্রতিটি বিনিময় আলোচনা, যৌথ সিদ্ধান্ত এবং পরবর্তী পদক্ষেপ এক জায়গায় রাখুন।", exchangeDescription:"গৃহীত মিলকে লজিস্টিকস, নিশ্চিতকরণ এবং প্রতিক্রিয়াসহ পরিষ্কার হস্তান্তরে পরিণত করুন।" },
  ja: { preview:"プレビュー", login:"ログイン", matchingTitle:"マッチング", messagesTitle:"メッセージ", exchangeTitle:"交換", explore:"探す", browseAll:"すべて見る", filters:"フィルター", addObject:"アイテムを追加", conversations:"会話", secureChat:"安全なチャット", matchingDescription:"自分が提供するものと他の人が求めるものを比較し、相性の良い交換を見つけましょう。", messagesDescription:"交換に関する会話、共有した決定、次の手順を一か所で管理できます。", exchangeDescription:"合意したマッチを、物流、確認、フィードバックを含む明確な受け渡しに進めます。" },
  ko: { preview:"미리보기", login:"로그인", matchingTitle:"매칭", messagesTitle:"메시지", exchangeTitle:"교환", explore:"둘러보기", browseAll:"모두 보기", filters:"필터", addObject:"물품 추가", conversations:"대화", secureChat:"안전한 채팅", matchingDescription:"내가 제공하는 것과 다른 사람이 원하는 것을 비교해 잘 맞는 교환을 찾아보세요.", messagesDescription:"각 교환 대화와 공동 결정, 다음 단계를 한곳에서 관리하세요.", exchangeDescription:"합의된 매칭을 물류, 확인, 피드백이 포함된 명확한 인계 과정으로 이어가세요." },
  vi: { preview:"Xem trước", login:"Đăng nhập", matchingTitle:"Ghép đôi", messagesTitle:"Tin nhắn", exchangeTitle:"Trao đổi", explore:"Khám phá", browseAll:"Xem tất cả", filters:"Bộ lọc", addObject:"Thêm đồ vật", conversations:"Cuộc trò chuyện", secureChat:"Trò chuyện an toàn", matchingDescription:"So sánh thứ bạn cung cấp với nhu cầu của người khác và khám phá các trao đổi phù hợp.", messagesDescription:"Giữ mọi cuộc trò chuyện trao đổi, quyết định chung và bước tiếp theo ở cùng một nơi.", exchangeDescription:"Biến một kết quả ghép đã đồng ý thành quy trình bàn giao rõ ràng với hậu cần, xác nhận và phản hồi." },
  th: { preview:"ตัวอย่าง", login:"เข้าสู่ระบบ", matchingTitle:"การจับคู่", messagesTitle:"ข้อความ", exchangeTitle:"การแลกเปลี่ยน", explore:"สำรวจ", browseAll:"ดูทั้งหมด", filters:"ตัวกรอง", addObject:"เพิ่มสิ่งของ", conversations:"การสนทนา", secureChat:"แชทปลอดภัย", matchingDescription:"เปรียบเทียบสิ่งที่คุณเสนอเข้ากับสิ่งที่ผู้อื่นกำลังมองหา และค้นหาการแลกเปลี่ยนที่เข้ากันได้", messagesDescription:"เก็บทุกการสนทนาเกี่ยวกับการแลกเปลี่ยน การตัดสินใจร่วมกัน และขั้นตอนถัดไปไว้ในที่เดียว", exchangeDescription:"เปลี่ยนการจับคู่ที่ตกลงแล้วให้เป็นการส่งมอบที่ชัดเจน พร้อมการจัดการ การยืนยัน และความคิดเห็น" },
  id: { preview:"Pratinjau", login:"Masuk", matchingTitle:"Kecocokan", messagesTitle:"Pesan", exchangeTitle:"Pertukaran", explore:"Jelajahi", browseAll:"Lihat semua", filters:"Filter", addObject:"Tambah barang", conversations:"Percakapan", secureChat:"Obrolan aman", matchingDescription:"Bandingkan apa yang Anda tawarkan dengan apa yang dicari orang lain dan temukan pertukaran yang cocok.", messagesDescription:"Simpan setiap percakapan pertukaran, keputusan bersama, dan langkah berikutnya di satu tempat.", exchangeDescription:"Ubah kecocokan yang disepakati menjadi serah terima yang jelas dengan logistik, konfirmasi, dan umpan balik." },
  ms: { preview:"Pratonton", login:"Log masuk", matchingTitle:"Padanan", messagesTitle:"Mesej", exchangeTitle:"Pertukaran", explore:"Teroka", browseAll:"Lihat semua", filters:"Penapis", addObject:"Tambah objek", conversations:"Perbualan", secureChat:"Sembang selamat", matchingDescription:"Bandingkan apa yang anda tawarkan dengan apa yang dicari orang lain dan temui pertukaran yang serasi.", messagesDescription:"Simpan setiap perbualan pertukaran, keputusan bersama dan langkah seterusnya di satu tempat.", exchangeDescription:"Tukar padanan yang dipersetujui menjadi penyerahan yang jelas dengan logistik, pengesahan dan maklum balas." },
  fil: { preview:"Preview", login:"Mag-sign in", matchingTitle:"Mga tugma", messagesTitle:"Mga mensahe", exchangeTitle:"Palitan", explore:"Tuklasin", browseAll:"Tingnan lahat", filters:"Mga filter", addObject:"Magdagdag ng bagay", conversations:"Mga pag-uusap", secureChat:"Ligtas na chat", matchingDescription:"Ihambing ang inaalok mo sa hinahanap ng iba at tumuklas ng mga tugmang palitan.", messagesDescription:"Panatilihin sa isang lugar ang bawat usapan sa palitan, magkakasamang desisyon, at susunod na hakbang.", exchangeDescription:"Gawing malinaw na pagpapalitan ang napagkasunduang match gamit ang logistics, kumpirmasyon, at feedback." },
  fa: { preview:"پیش‌نمایش", login:"ورود", matchingTitle:"تطبیق‌ها", messagesTitle:"پیام‌ها", exchangeTitle:"مبادله", explore:"کاوش", browseAll:"مشاهده همه", filters:"فیلترها", addObject:"افزودن شیء", conversations:"گفتگوها", secureChat:"گفتگوی امن", matchingDescription:"آنچه ارائه می‌دهید را با نیاز دیگران مقایسه کنید و مبادله‌های سازگار را پیدا کنید.", messagesDescription:"هر گفت‌وگوی مبادله، تصمیم‌های مشترک و گام‌های بعدی را در یک مکان نگه دارید.", exchangeDescription:"یک تطبیق پذیرفته‌شده را با هماهنگی، تأیید و بازخورد به تحویلی روشن تبدیل کنید." },
  mn: { preview:"Урьдчилан харах", login:"Нэвтрэх", matchingTitle:"Тохирлууд", messagesTitle:"Зурвасууд", exchangeTitle:"Солилцоо", explore:"Судлах", browseAll:"Бүгдийг харах", filters:"Шүүлтүүр", addObject:"Зүйл нэмэх", conversations:"Ярианууд", secureChat:"Аюулгүй чат", matchingDescription:"Өөрийн санал болгож буй зүйлийг бусдын хайж буй зүйлтэй харьцуулж, тохирох солилцоог олоорой.", messagesDescription:"Солилцооны бүх яриа, хамтын шийдвэр болон дараагийн алхмуудыг нэг дор хадгалаарай.", exchangeDescription:"Зөвшөөрсөн тохирлыг логистик, баталгаажуулалт, санал хүсэлттэй тодорхой хүлээлгэн өгөх үйл явц болгоорой." },
  uk: { preview:"Попередній перегляд", login:"Увійти", matchingTitle:"Збіги", messagesTitle:"Повідомлення", exchangeTitle:"Обмін", explore:"Огляд", browseAll:"Переглянути все", filters:"Фільтри", addObject:"Додати об’єкт", conversations:"Розмови", secureChat:"Безпечний чат", matchingDescription:"Порівняйте те, що пропонуєте, з тим, що шукають інші, і знайдіть сумісні обміни.", messagesDescription:"Зберігайте всі розмови про обмін, спільні рішення та наступні кроки в одному місці.", exchangeDescription:"Перетворіть погоджений збіг на зрозумілу передачу з логістикою, підтвердженням і відгуком." },
  yi: { preview:"פֿאָרויסקוק", login:"אַרײַנלאָגירן", matchingTitle:"פּאַסונגען", messagesTitle:"אַרטיקלען", exchangeTitle:"אויסטויש", explore:"אויספֿאָרשן", browseAll:"זען אַלע", filters:"פֿילטערס", addObject:"צולייגן אַ זאַך", conversations:"שמועסן", secureChat:"זיכערער שמועס", matchingDescription:"פֿאַרגלײַכט וואָס איר אָפֿערט מיט וואָס אַנדערע זוכן און געפֿינט פּאַסיקע אויסטוישן.", messagesDescription:"האַלט אַלע אויסטויש־שמועסן, געמיינזאמע באַשלוסן און קומענדיקע שריט אויף איין אָרט.", exchangeDescription:"מאַכט פֿון אַ מסכּים־געוואָרענעם פּאַס אַ קלאָרע איבערגעבן מיט לאָגיסטיק, באַשטעטיקונג און באַמערקונגען." },
} as const satisfies Record<Locale, PublicCoreUi>;

export function getPublicCoreUi(locale: string): PublicCoreUi {
  const normalized = locale.toLowerCase().split("-")[0] as Locale;
  return locales.includes(normalized) ? publicCoreUi[normalized] : publicCoreUi.en;
}
