import type { IntegrationAuditCheck } from "./integrationAuditTypes";

export const INTEGRATION_AUDIT_V2_CHECKS = [
  {
    id: "audit-human-centered-advisory",
    area: "human_centered_swapping",
    label: "Human-centered swapping remains advisory and optional.",
    status: "pass",
    evidence: "Meaning match explanations require human decision and optional personal context.",
    blocking: true,
  },
  {
    id: "audit-advanced-swaps-consent",
    area: "advanced_swap_modes",
    label: "Advanced swaps require all participant consent.",
    status: "pass",
    evidence: "Circular and chain swaps cannot move to exchange without all participants accepting.",
    blocking: true,
  },
  {
    id: "audit-photo-discovery-non-blocking",
    area: "photo_discovery",
    label: "Photo discovery does not block manual item creation.",
    status: "pass",
    evidence: "Manual item creation remains available when AI photo discovery is unavailable.",
    blocking: true,
  },
  {
    id: "audit-guided-chat-original",
    area: "guided_chat",
    label: "Guided chat is optional and preserves original text.",
    status: "pass",
    evidence: "Free text remains allowed and translated helper content does not replace original messages.",
    blocking: true,
  },
  {
    id: "audit-exchange-no-auto-complete",
    area: "exchange_lifecycle",
    label: "Exchange lifecycle cannot auto-complete.",
    status: "pass",
    evidence: "Completion gates require checklist, participant confirmations and human confirmation.",
    blocking: true,
  },
  {
    id: "audit-token-rank-separated",
    area: "token_rank_separation",
    label: "Tokens cannot buy or convert into rank.",
    status: "pass",
    evidence: "Rank evaluation ignores token balance and relies on trust signals.",
    blocking: true,
  },
  {
    id: "audit-blog-structured-only",
    area: "blog_suggestions",
    label: "Blog feedback remains structured and moderated.",
    status: "pass",
    evidence: "Public free-text comments are disabled and suggestions require editorial review.",
    blocking: true,
  },
  {
    id: "audit-ai-evals-fallbacks",
    area: "ai_evals",
    label: "AI evals enforce fallback and advisory-only behavior.",
    status: "pass",
    evidence: "Safety/privacy thresholds and fallback readiness are part of AI evaluation.",
    blocking: true,
  },
  {
    id: "audit-language-global-first",
    area: "language_fallback",
    label: "Missing exact translations do not block public pages.",
    status: "pass",
    evidence: "Language fallback resolves to available content and keeps chat originals visible.",
    blocking: true,
  },
] as const satisfies readonly IntegrationAuditCheck[];
