export type PropertyFormData = {
  // Step 1 — Type & Classification
  property_type: string;
  property_subtype: string;
  property_category: string;
  year_built: string;
  last_renovated: string;
  renovation_details: string;

  // Step 2 — Location & GPS
  country: string;
  region: string;
  city: string;
  address_line1: string;
  lat: string;
  lon: string;
  location_type: string[];
  proximity_sea_km: string;
  proximity_mountain_km: string;
  proximity_forest_km: string;
  distance_to_center_km: string;
  nearest_airport_code: string;

  // Step 3 — Structure & Rooms
  total_buildings: number;
  building_condition: string;
  construction_material: string[];
  floor_count: number;
  property_floor: number;
  has_elevator: boolean;
  bedrooms: number;
  bathrooms: number;
  toilets_extra: number;
  living_rooms: number;
  kitchen_count: number;
  office_rooms: number;
  storage_rooms: number;
  total_area_sqm: string;
  living_area_sqm: string;
  garden_area_sqm: string;
  terrace_area_sqm: string;
  pool_area_sqm: string;

  // Step 4 — Amenities & Features
  has_swimming_pool: boolean;
  pool_type: string;
  has_hot_tub: boolean;
  has_sauna: boolean;
  has_gym: boolean;
  has_tennis_court: boolean;
  has_playground: boolean;
  has_bbq_area: boolean;
  outdoor_fireplace: boolean;
  outdoor_kitchen: boolean;
  has_garden: boolean;
  parking_spaces: number;
  garage_type: string;
  ev_charging: boolean;
  parking_distance_m: string;
  kitchen_appliances: string[];
  bed_types: string[];
  mattress_quality: string;
  linen_provided: boolean;
  towels_provided: boolean;
  extra_pillows: boolean;
  furnishing_level: string;

  // Step 5 — Utilities & Systems
  heating_type: string[];
  cooling_type: string[];
  water_source: string;
  hot_water_system: string;
  electricity_source: string[];
  solar_panels: boolean;
  solar_capacity_kw: string;
  internet_type: string;
  internet_speed_mbps: string;
  smart_home_features: boolean;
  smart_home_details: string;
  eco_certifications: string[];
  backup_generator: boolean;
  septic_tank: boolean;

  // Step 6 — Exchange Terms
  exchange_type: string;
  exchange_duration: string[];
  minimum_stay_days: string;
  maximum_stay_days: string;
  preferred_seasons: string[];
  number_of_guests_allowed: number;
  flexible_dates: boolean;
  available_start_date: string;
  available_end_date: string;
  advance_booking_days: string;
  desired_exchange_destination: string;
  desired_exchange_country: string;
  desired_exchange_description: string;
  escrow_accepted: boolean;
  escrow_required: boolean;
  security_deposit_eur: string;
  swap_geo_preference: string;
  swap_partial_allowed: boolean;
  swap_partial_topup_eur: string;
  chain_swap_allowed: boolean;

  // Step 7 — Rules & Policies
  check_in_time: string;
  check_out_time: string;
  smoking_allowed: string;
  alcohol_allowed: boolean;
  parties_allowed: boolean;
  quiet_hours: string;
  guests_limit: number;
  children_allowed: boolean;
  min_child_age: string;
  infants_allowed: boolean;
  pets_allowed: boolean;
  pets_types: string[];
  local_wildlife_note: string;
  smoking_outdoor_area: boolean;
  housekeeping_included: boolean;
  housekeeping_frequency: string;
  security_system: boolean;
  cctv_present: boolean;
  cctv_disclosure: string;
  keypad_entry: boolean;
  wifi_password: string;
  emergency_contact_available: boolean;
  special_house_rules: string;
  accessibility_features: string[];

  // Step 8 — Confirmation
  confirm_vacation_only: boolean;
  confirm_accurate_info: boolean;
  confirm_terms: boolean;
  cross_category_swap: boolean;
};

export const INITIAL_FORM: PropertyFormData = {
  property_type: "",
  property_subtype: "",
  property_category: "",
  year_built: "",
  last_renovated: "",
  renovation_details: "",
  country: "",
  region: "",
  city: "",
  address_line1: "",
  lat: "",
  lon: "",
  location_type: [],
  proximity_sea_km: "",
  proximity_mountain_km: "",
  proximity_forest_km: "",
  distance_to_center_km: "",
  nearest_airport_code: "",
  total_buildings: 1,
  building_condition: "",
  construction_material: [],
  floor_count: 1,
  property_floor: 0,
  has_elevator: false,
  bedrooms: 1,
  bathrooms: 1,
  toilets_extra: 0,
  living_rooms: 1,
  kitchen_count: 1,
  office_rooms: 0,
  storage_rooms: 0,
  total_area_sqm: "",
  living_area_sqm: "",
  garden_area_sqm: "",
  terrace_area_sqm: "",
  pool_area_sqm: "",
  has_swimming_pool: false,
  pool_type: "",
  has_hot_tub: false,
  has_sauna: false,
  has_gym: false,
  has_tennis_court: false,
  has_playground: false,
  has_bbq_area: false,
  outdoor_fireplace: false,
  outdoor_kitchen: false,
  has_garden: false,
  parking_spaces: 0,
  garage_type: "None",
  ev_charging: false,
  parking_distance_m: "",
  kitchen_appliances: [],
  bed_types: [],
  mattress_quality: "",
  linen_provided: false,
  towels_provided: false,
  extra_pillows: false,
  furnishing_level: "",
  heating_type: [],
  cooling_type: [],
  water_source: "",
  hot_water_system: "",
  electricity_source: [],
  solar_panels: false,
  solar_capacity_kw: "",
  internet_type: "",
  internet_speed_mbps: "",
  smart_home_features: false,
  smart_home_details: "",
  eco_certifications: [],
  backup_generator: false,
  septic_tank: false,
  exchange_type: "",
  exchange_duration: [],
  minimum_stay_days: "",
  maximum_stay_days: "",
  preferred_seasons: [],
  number_of_guests_allowed: 2,
  flexible_dates: false,
  available_start_date: "",
  available_end_date: "",
  advance_booking_days: "",
  desired_exchange_destination: "",
  desired_exchange_country: "",
  desired_exchange_description: "",
  escrow_accepted: false,
  escrow_required: false,
  security_deposit_eur: "",
  swap_geo_preference: "",
  swap_partial_allowed: false,
  swap_partial_topup_eur: "",
  chain_swap_allowed: false,
  check_in_time: "15:00",
  check_out_time: "11:00",
  smoking_allowed: "Not Allowed",
  alcohol_allowed: true,
  parties_allowed: false,
  quiet_hours: "",
  guests_limit: 4,
  children_allowed: true,
  min_child_age: "",
  infants_allowed: true,
  pets_allowed: false,
  pets_types: [],
  local_wildlife_note: "",
  smoking_outdoor_area: false,
  housekeeping_included: false,
  housekeeping_frequency: "",
  security_system: false,
  cctv_present: false,
  cctv_disclosure: "",
  keypad_entry: false,
  wifi_password: "",
  emergency_contact_available: true,
  special_house_rules: "",
  accessibility_features: [],
  confirm_vacation_only: false,
  confirm_accurate_info: false,
  confirm_terms: false,
  cross_category_swap: false,
};

export const DRAFT_STORAGE_KEY = "swaply_property_wizard_draft";
